name: ML CI/CT/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  continuous-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8

      # Lint
      - name: Lint code
        run: |
          flake8 src/

      # Unit tests (optional)
      - name: Run tests
        run: |
          pytest tests/ || echo "No tests yet"


  train-test:
    needs: continuous-testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Train
      - name: Train model
        run: |
          python src/train.py

      # Evaluate
      - name: Evaluate model
        run: |
          python src/evaluate.py

      # Upload artifacts
      - name: Upload ML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifacts
          path: |
            model/model.pkl
            data/split/


  docker-build:
    needs: train-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download artifacts
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ml-artifacts

      # Docker login
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image
      - name: Build image
        run: |
          docker build -t surbhibagad/soil-ml:latest .

      # Push image
      - name: Push image
        run: |
          docker push surbhibagad/soil-ml:latest